spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zxb_sys?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sifu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
